# Aprendizaje Automático
## Segunda práctica guiada
---
Para la segunda práctica del curso de aprendizaje automático, se utilizará el mismo conjunto de datos que pertenece al repositorio especial de Machine Learning de la [UCI](https://archive.ics.uci.edu/ml). El conjunto de datos se llama "Adult" y toda la información correspondiente al mismo se encuentra [aquí](https://archive.ics.uci.edu/ml/datasets/Adult).

---
### Árboles de Decisión y Regresión

Un árbol de decisión es un árbol donde cada nodo representa una característica (atributo), cada enlace (rama) representa una decisión (regla) y cada hoja representa un resultado (valor categórico o continuo).

Los DT (Decision Trees) son ampliamente usados en Machine Learning para resolver problemas de clasificación y regresión. En la segunda práctica del curso de Aprendizaje Automático se construirán Árboles de Decisión en Python con la librería sci-kit learn y con el conjunto de datos suministrado.

En principio, importamos todas las librerías necesarias para trabajar Aprendizaje Automático con Python y Sci-kit learn

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
import itertools
from sklearn import metrics
from sklearn import preprocessing
from sklearn import tree
from sklearn import svm
import io
import requests

Luego procedemos a importar los datos de entrenamiento y eliminar los valores faltantes, además de convertir los valores categóricos a enteros.

In [5]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
ds_ = pd.read_csv(url, header=None, na_values=" ?")
ds = ds_.dropna()
ds = ds.rename(columns = {ds.columns.values[14]:'C'}) # Cambiamos el nombre de la última columna por "C" de clase
le = preprocessing.LabelEncoder() # Label encoder de sci-kit
ds = ds.apply(le.fit_transform) # Convertimos los valores de object a int
ds

        0  1      2   3   4  5   6  7  8  9   10  11  12  13  C
0      22  5   2491   9  12  4   0  1  4  1   24   0  39  38  0
1      33  4   2727   9  12  2   3  0  4  1    0   0  12  38  0
2      21  2  13188  11   8  0   5  1  4  1    0   0  39  38  0
3      36  2  14354   1   6  2   5  0  2  1    0   0  39  38  0
4      11  2  18120   9  12  2   9  5  2  0    0   0  39   4  0
5      20  2  16567  12  13  2   3  5  4  0    0   0  39  38  0
6      32  2   7982   6   4  3   7  1  2  0    0   0  15  22  0
7      35  4  12746  11   8  2   3  0  4  1    0   0  44  38  1
8      14  2   1225  12  13  4   9  1  4  0  104   0  49  38  1
9      25  2   7908   9  12  2   3  0  4  1   78   0  39  38  1
10     20  2  16411  15   9  2   3  0  2  1    0   0  76  38  1
11     13  5   6629   9  12  2   9  0  1  1    0   0  39  18  1
12      6  2   5399   9  12  4   0  3  4  0    0   0  29  38  0
13     15  2  12364   7  11  4  11  1  2  1    0   0  49  38  0
15     17  2  14951   5   3  2  13  0  0  1    0   0  44  25  0
16      8  4   9507  11   8  4   4  3  4  1    0   0  34  38  0
17     15  2  10533  11   8  4   6  4  4  1    0   0  39  38  0
18     21  2    292   1   6  2  11  0  4  1    0   0  49  38  0
19     26  4  16831  12  13  0   3  4  4  0    0   0  44  38  1
20     23  2  11280  10  15  2   9  0  4  1    0   0  59  38  1
21     37  2  17134  11   8  5   7  4  2  0    0   0  19  38  0
22     18  0   2457   6   4  2   4  0  2  1    0   0  39  38  0
23     26  2   4963   1   6  2  13  0  4  1    0  54  39  38  0
24     42  2   4309  11   8  0  12  4  4  0    0   0  39  38  0
25     39  1  13274   9  12  2  12  0  4  1    0   0  39  38  1
26      2  2   8667  11   8  4   2  3  4  1    0   0  39  38  0
28     22  2  18795  11   8  0   3  1  4  1    0   0  76  38  0
29     32  2  11265  11   8  2   2  0  4  1    0   0  39  38  0
30      6  1  10970   7  11  4  10  1  4  1    0   0  51  38  0
31      3  2  15818  15   9  4  11  3  2  1    0   0  43  38  0
...    .. ..    ...  ..  .. ..  .. .. .. ..  ...  ..  ..  .. ..
32526  15  2  12879   0   5  2  13  0  4  1    0   0  39  38  0
32527   5  2  12252  15   9  4   0  3  4  1    0   0  39  38  0
32528  14  2  16847  11   8  2   6  5  4  0    0   0  39  38  0
32529  12  2   5649  11   8  5  11  4  4  0    0   0  34  38  0
32532  17  2  12317  10  15  2   9  0  4  1    0   0  59  38  1
32533  37  2  18108   9  12  2   3  0  1  1    0   0  49  23  1
32534  20  2   9751  15   9  0   0  4  4  0    0   0  38  38  0
32535   5  2  17787   2   7  4  10  3  2  1    0   0  34  38  0
32536  17  2   7984   9  12  4   3  1  4  0    0   0  54  38  1
32537  13  2  18343  11   8  4   2  1  2  1    0   0  45  38  0
32538  21  2   6502   9  12  0   9  4  2  0  106   0  44  38  1
32540  28  5  15249  11   8  5   0  3  4  0    0   0  39  38  0
32543  28  1   5171   7  11  0   9  4  4  0    0   0  47  38  0
32544  14  2  11894  12  13  0   7  1  3  0    0   0  29  38  0
32545  22  1   4519   7  11  2   0  5  4  0    0   0  19  38  1
32546  20  2  11741   7  11  0  12  1  4  0    0   0  39  38  0
32547  26  2  15617  11   8  2   6  0  4  1    0   0  39  25  0
32548  48  4   3556  14  14  4   9  1  4  1    7   0  59  38  0
32549  26  5  15404  15   9  0   0  2  4  0    0   0  39  38  0
32550  26  4    214  15   9  2   2  0  4  1    0   0  49  38  0
32551  15  2    648   0   5  2   5  0  0  1    0   0  39  38  0
32552  26  2   2802   8  10  2  11  0  4  1    0   0  44  38  0
32553  15  2   4886  12  13  4  12  1  1  1    0   0  10  35  0
32554  36  2  17708  12  13  2   3  0  4  1    0   0  39  38  1
32555   5  2  17375  15   9  4  10  1  4  1    0   0  39  38  0
32556  10  2  15471   7  11  2  12  5  4  0    0   0  37  38  0
32557  23  2   7555  11   8  2   6  0  4  1    0   0  39  38  1
32558  41  2   7377  11   8  6   0  4  4  0    0   0  39  38  0
32559   5  2  12060  11   8  4   0  3  4  1    0   0  19  38  0
32560  35  3  16689  11   8  2   3  5  4  0  107   0  39  38  1

[30162 rows x 15 columns]

Importamos los datos de prueba de la misma manera que importamos los datos de entrenamiento.

In [6]:
urltest = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test"
test_ = pd.read_csv(urltest, skiprows=1, header=None, na_values=" ?")
test = test_.dropna()
test = test.rename(columns = {test.columns.values[14]:'C'}) # Cambiamos el nombre de la última columna por "C" de clases = test.apply(le.fit_transform) # Convertimos los valores de object a int
test = test.apply(le.fit_transform) # Convertimos los valores de object a int
test

        0  1      2   3   4  5   6  7  8  9   10  11  12  13  C
0       8  2   8315   1   6  4   6  3  2  1    0   0  39  37  0
1      21  2   1754  11   8  2   4  0  4  1    0   0  49  37  0
2      11  1  10750   7  11  2  10  0  4  1    0   0  39  37  1
3      27  2   4780  15   9  2   6  0  2  1   87   0  39  37  1
5      17  2   7091   0   5  4   7  1  4  1    0   0  29  37  0
7      46  4   2342  14  14  2   9  0  4  1   44   0  31  37  1
8       7  2  11153  15   9  4   7  4  4  0    0   0  39  37  0
9      38  2   2361   5   3  2   2  0  4  1    0   0   9  37  0
10     48  2   6199  11   8  2   6  0  4  1   77   0  39  37  1
11     19  0   7773   9  12  2   0  0  4  1    0   0  39  37  0
12      9  2   1548  11   8  4   0  1  4  0    0   0  38  37  0
14     31  2   9790  11   8  2   6  0  4  1   44   0  47  37  1
15     26  2  10882  12  13  2   3  0  4  1    0   0  49  37  1
16      3  5  11624  15   9  4   7  3  4  1    0   0  24  37  0
17     26  2   3425  11   8  2   0  5  4  0    0   0  29  37  0
18     20  2   1093  11   8  6   6  4  4  0    0   0  19  37  0
20     17  2   2508   9  12  2  12  0  4  1    0   0  46  37  1
21     17  2   8718  15   9  4   7  3  2  0    0   0  34  37  0
23      8  2   8107   9  12  4   9  1  4  1    0   0  42  27  0
24      8  2   7488   9  12  2   9  0  4  1    0   0  39  37  0
25     28  4  11575  11   8  2   2  0  4  1   84   0  84  37  1
26      5  2   8648  11   8  4   0  3  4  1    0   0  19  37  0
27      6  2   3666  11   8  5   6  4  2  1    0   0  53  37  0
28     37  2   2092  11   8  2   2  0  4  1    0   0  34  37  0
29     15  4   2574  15   9  4   9  1  4  1    0   0  59  37  0
30     29  5   2430  15   9  2   3  0  2  1   87   0  37  37  1
31     39  4   6335   1   6  6   7  4  4  0    0   0  49  37  0
32      7  4   6452   9  12  4  11  1  4  1    0   0  49  37  0
33      6  1   9267  15   9  2  10  0  4  1    0   0  39  37  0
34      9  2    640  11   8  0   3  4  4  0    0   0  39  37  0
...    .. ..    ...  ..  .. ..  .. .. .. ..  ...  ..  ..  .. ..
16248   8  2   8822  11   8  0   6  1  2  1    0   0  39  37  0
16249  14  2   2709  11   8  4   6  1  4  1    0   0  39  37  0
16250  32  3   1436  11   8  2   3  0  4  1    0   0  39   1  1
16252  43  2   3009   8  10  2   9  0  4  1   87   0  39  37  1
16253  22  2   8429   9  12  4  12  1  4  0    0  27  39  37  0
16254  21  2   4270  12  13  2   9  0  4  1    0   0  49  37  1
16255  26  1     51  12  13  2   3  0  4  1    0  42  49  37  1
16256   6  2   1870  11   8  4   6  3  4  1    0   0  39  37  0
16257  56  3   4751  15   9  0   3  1  4  0    0   0  39  37  0
16258  18  2   5733  15   9  2  10  0  4  1    0   0  39  37  0
16259  49  2  10860  11   8  6  11  2  4  0    0   0   7  37  0
16260  10  2  11565  15   9  4  11  1  4  0    0   0  44  37  0
16261  23  2   7310  14  14  2   9  0  4  1  101   0  54  37  1
16262  34  2   1563  11   8  2   2  0  4  1    0   0  39  37  0
16263   5  2   9562  15   9  4   2  3  4  1    0   0  39  37  0
16264  47  4   3745  11   8  6   4  1  4  1    0   0  31  37  0
16266  38  2   8237  11   8  5   8  1  4  0    0   0  31  37  0
16267  21  2   8985   8  10  4   0  4  2  0    0   0  39  37  0
16268  41  2  10042   7  11  0   9  1  4  1    0   0  35  37  0
16269  15  2   5485  11   8  2   5  0  4  1    0   0  39  37  0
16270  31  2   9901  11   8  2   0  0  4  1    0   0  39  37  0
16271  44  2   1749  11   8  2  11  0  4  1    0   0  47  37  0
16272  14  2  11608  11   8  2   2  0  4  1    0   0  39  37  0
16273   8  2  10942  11   8  4   7  3  4  0    0   0  39  37  0
16274  31  1  10923  12  13  0   7  1  4  1    0   0  39  37  0
16275  16  2   8927   9  12  4   9  3  4  1    0   0  39  37  0
16276  22  2   7893   9  12  0   9  1  4  0    0   0  35  37  0
16278  21  2  11193   9  12  2   9  0  4  1    0   0  49  37  0
16279  27  2   1593   9  12  0   0  3  1  1   73   0  39  37  0
16280  18  3   6062   9  12  2   3  0  4  1    0   0  59  37  1

[15060 rows x 15 columns]

En la siguiente porción de código, entrenamos el clasificador y realizamos la respectiva predicción teniendo en cuenta los datos de prueba. Además, evaluamos el desempeño del clasificador teniendo en cuenta las métricas que provee el reporte de clasificación de sklearn

In [7]:

################################################################
#################### ÁRBOL DE DECISIÓN #########################
################################################################

x_train = ds.drop('C', axis = 1)
y_train = ds['C']

x_test = test.drop('C', axis = 1)
y_test = test['C']

class_names = ['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education-num', 'Marital-status', 'Occupation',
              'Relationship', 'Race', 'Sex', 'Capital-gain', 'Capital-loss', 'Hpw', 'Country']

DT_clf = tree.DecisionTreeClassifier()
DT_clf.fit(x_train, y_train)


DT_predict = DT_clf.predict(x_test)

print("\n############## Accuracy DT##################")
print(metrics.accuracy_score(y_test, DT_predict))
print("\n############## Matriz de Confusion DT ##################")
print(metrics.confusion_matrix(y_test, DT_predict))  
print("\n############## Metricas DT ##################")
print(metrics.classification_report(y_test, DT_predict))

############## Accuracy DT##################
0.7983399734395751

############## Matriz de Confusion DT ##################
[[9871 1489]
 [1548 2152]]

############## Metricas DT ##################
              precision    recall  f1-score   support

           0       0.86      0.87      0.87     11360
           1       0.59      0.58      0.59      3700

   micro avg       0.80      0.80      0.80     15060
   macro avg       0.73      0.73      0.73     15060
weighted avg       0.80      0.80      0.80     15060

Ahora, realizamos el entrenamiento y predicción del árbol de regresión.

In [5]:
DT_reg = tree.DecisionTreeRegressor()  
DT_reg.fit(x_train, y_train)
DT_predict = DT_reg.predict(x_test) 
df=pd.DataFrame({'Actual':y_test, 'Predicted':DT_predict})  
df

       Actual  Predicted
0           0        0.0
1           0        0.0
2           1        0.0
3           1        1.0
5           0        0.0
7           1        1.0
8           0        0.0
9           0        0.0
10          1        0.0
11          0        1.0
12          0        0.0
14          1        1.0
15          1        1.0
16          0        0.0
17          0        1.0
18          0        0.0
20          1        1.0
21          0        0.0
23          0        0.0
24          0        0.0
25          1        1.0
26          0        0.0
27          0        0.0
28          0        1.0
29          0        0.0
30          1        1.0
31          0        0.0
32          0        0.0
33          0        0.0
34          0        0.0
...       ...        ...
16248       0        0.0
16249       0        0.0
16250       1        1.0
16252       1        1.0
16253       0        0.0
16254       1        1.0
16255       1        1.0
16256       0        0.0
16257       0        0.0
16258       0        0.0
16259       0        0.0
16260       0        1.0
16261       1        1.0
16262       0        0.0
16263       0        0.0
16264       0        0.0
16266       0        0.0
16267       0        0.0
16268       0        0.0
16269       0        1.0
16270       0        0.0
16271       0        0.0
16272       0        0.0
16273       0        0.0
16274       0        0.0
16275       0        0.0
16276       0        0.0
16278       0        1.0
16279       0        1.0
16280       1        1.0

[15060 rows x 2 columns]

Por último, podemos comprobar el desempeño del regresor con las métricas MAE, MSE y RMSE.

In [8]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, DT_predict))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, DT_predict))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, DT_predict)))

Mean Absolute Error: 0.20166002656042498
Mean Squared Error: 0.20166002656042498
Root Mean Squared Error: 0.4490657263256961

In [11]:
DT_clf.fit

<bound method DecisionTreeClassifier.fit of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')>